version: "3.3"

services:
  gbans-test:
    build:
      context: "../"
      dockerfile: ./docker/test.Dockerfile
    volumes:
      - dl_cache:/app/.cache
    depends_on:
      - postgres
    networks:
      - test_network
    environment:
      GBANS_DATABASE_DSN: postgresql://gbans:gbans@postgres:5434/gbans
      GBANS_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: ["make", "test"]

  postgres:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    expose:
      - "5434"
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
    networks:
      - test_network
    command: "-p 5434"

volumes:
  dl_cache:

networks:
  test_network:
