version: "3.3"

services:
  gbans-test:
    build:
      context: "../"
      dockerfile: ./docker/test.Dockerfile
    depends_on:
      - postgres-test
    networks:
      - test_network
    environment:
      GBANS_DATABASE_DSN: postgresql://gbans:gbans@postgres-test:5434/gbans
      GBANS_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: ["make", "test"]

  postgres-test:
    image: postgis/postgis:13-3.1-alpine
    restart: always
    expose:
      - "5434"
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
    networks:
      - test_network
    command: "-p 5434"

networks:
  test_network:
