version: "3.3"

services:
  gbans:
    build:
      context: "../"
      dockerfile: Dockerfile
    volumes:
      - dl_cache:/app/.cache
      - ./gbans.yml:/app/gbans.yml
    depends_on:
      - postgres
    networks:
      - prod_network
    environment:
      GBANS_DATABASE_DSN: postgresql://gbans:gbans@postgres:5432/gbans
      GBANS_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: ./gbans serve
  postgres:
    image: postgis/postgis:15-3.3
    restart: always
    #volumes:
    #  - gbans_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
    networks:
      - prod_network

volumes:
  dl_cache:
  gbans_db:

networks:
  prod_network:
