name: Docker Image CI

on: [push]

jobs:
  docker-test:
    runs-on: ubuntu-latest
    env:
      GBANS_GENERAL_STEAM_KEY: ${{ secrets.GBANS_GENERAL_STEAM_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Build the docker-compose stack
        run: make docker_test
