name: TS / Go Linters

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      GBANS_GENERAL_STEAM_KEY: ${{ secrets.GBANS_GENERAL_STEAM_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        working-directory: ./frontend
        run: yarn

      - name: Prettier
        working-directory: ./frontend
        run: yarn run prettier:check

      - name: ESLint
        working-directory: ./frontend
        run: yarn run eslint:check

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.1

