---
name: "release"

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  pre-release:
    name: "gbans Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build gbans
        run: make dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workflow }}-CHANGELOG.md
          prerelease: true
          files: |
            gbans-*.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_REPOSITORY: leighmacdonald/gbans
